wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641649094
    t:
      1:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: vit
batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0001
mom:
  desc: null
  value: 0.9
optimizer:
  desc: null
  value: adam
res_pretrain:
  desc: null
  value: false
vit_architecture:
  desc: null
  value: vit_base_patch16_224
vit_pretrain:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0
